"""Deterministic report retrieval."""

from .retrieval import RetrievalEngine, RetrievalResult
from .evidence import (
    EncryptedPdfError,
    EvidenceBlock,
    EvidenceDocument,
    EvidenceError,
    EvidencePage,
    EvidenceWord,
    InvalidPageRangeError,
    NoUsableTextError,
    PdfEvidenceExtractor,
    UnreadablePdfError,
)
from .revisions import (
    EstimateRevision,
    RevisionEvidence,
    RevisionExtractor,
    RevisionResult,
    calculate_consensus_spread,
    calculate_revision_pct,
    normalize_fiscal_period,
    normalize_metric,
    normalize_unit,
    parse_value,
)
from .rationale import (
    CandidatePassage,
    CandidatePassageSelector,
    DeterministicFakeRationaleModel,
    Driver,
    GroundedClaim,
    JargonDefinition,
    LocalOpenAICompatibleRationaleModel,
    ModelConfigurationError,
    ModelResponseError,
    PersonMet,
    RationaleExtraction,
    RationaleExtractor,
    RationaleInputError,
    RationaleModel,
    RationaleResult,
    detect_context_signals,
)
from .citations import (
    CitationBuildResult,
    CitationBuilder,
    CitationError,
    CitationInputError,
    CitationNotFoundError,
    CitationRecord,
    CitationRepository,
    CitationRequest,
    CitationStore,
    StaleCitationError,
    make_server,
    requests_from_rationale,
    requests_from_metadata,
    requests_from_revisions,
    source_fingerprint,
)
from .metadata import AnalystMetadata, ReportMetadata, ReportMetadataExtractor
from .brief import (
    BriefAnalyst,
    BriefCitation,
    BriefRevisionRow,
    EstimateVisualization,
    ResearchBrief,
    ResearchBriefBuilder,
    make_estimate_visualization,
    render_markdown,
    render_text as render_brief_text,
)

__all__ = [
    "EncryptedPdfError", "EvidenceBlock", "EvidenceDocument", "EvidenceError",
    "EvidencePage", "EvidenceWord", "InvalidPageRangeError", "NoUsableTextError",
    "PdfEvidenceExtractor", "UnreadablePdfError",
    "RetrievalEngine", "RetrievalResult",
    "EstimateRevision", "RevisionEvidence", "RevisionExtractor", "RevisionResult",
    "calculate_consensus_spread", "calculate_revision_pct", "normalize_fiscal_period",
    "normalize_metric", "normalize_unit", "parse_value",
    "CandidatePassage", "CandidatePassageSelector", "DeterministicFakeRationaleModel",
    "Driver", "GroundedClaim", "JargonDefinition", "LocalOpenAICompatibleRationaleModel",
    "ModelConfigurationError", "ModelResponseError", "PersonMet", "RationaleExtraction",
    "RationaleExtractor", "RationaleInputError", "RationaleModel", "RationaleResult",
    "detect_context_signals",
    "CitationBuildResult", "CitationBuilder", "CitationError", "CitationInputError",
    "CitationNotFoundError", "CitationRecord", "CitationRepository", "CitationRequest",
    "CitationStore", "StaleCitationError", "make_server", "requests_from_rationale",
    "requests_from_revisions", "requests_from_metadata", "source_fingerprint",
    "AnalystMetadata", "ReportMetadata", "ReportMetadataExtractor",
    "BriefAnalyst", "BriefCitation", "BriefRevisionRow", "EstimateVisualization",
    "ResearchBrief", "ResearchBriefBuilder", "make_estimate_visualization",
    "render_markdown", "render_brief_text",
]
